# Generated by Django 5.0.4 on 2026-10-05 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Título Acadêmico')),
                ('author', models.CharField(db_index=True, max_length=255, verbose_name='Autor(es)')),
                ('category', models.CharField(choices=[('COMPUTACAO', 'Ciência da Computação & IA'), ('ENGENHARIA', 'Engenharia de Software & Sistemas'), ('SEGURANCA', 'Criptografia, Redes & Tor'), ('ECONOMIA', 'Economia & Teoria Monetária'), ('DIREITO', 'Direito, Privacidade & Sociedade'), ('MATEMATICA', 'Matemática & Teoria da Informação'), ('FILOSOFIA', 'Filosofia da Ciência & Epistemologia')], db_index=True, max_length=30, verbose_name='Área de Conhecimento')),
                ('file_type', models.CharField(choices=[('PDF', 'Portable Document Format (.pdf)'), ('EPUB', 'Electronic Publication (.epub)'), ('DOCX', 'Microsoft Word Document (.docx)')], default='PDF', max_length=10, verbose_name='Formato')),
                ('file_size_bytes', models.BigIntegerField(verbose_name='Tamanho (Bytes)')),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Content Hash (SHA-256)')),
                ('chunk_size_bytes', models.IntegerField(default=524288, verbose_name='Tamanho do Chunk (Bytes)')),
                ('total_chunks', models.IntegerField(verbose_name='Total de Chunks')),
                ('cipher', models.CharField(default='XChaCha20-Poly1305', max_length=50, verbose_name='Algoritmo de Cifra')),
                ('swarm_link', models.CharField(blank=True, max_length=600, verbose_name='Link de Swarm (opocswarm://)')),
                ('publication_year', models.IntegerField(default=2024, verbose_name='Ano da Publicação')),
                ('total_downloads', models.IntegerField(default=0, verbose_name='Downloads Totais')),
                ('total_seeds_active', models.IntegerField(default=1, verbose_name='Seeders Ativos')),
            ],
            options={
                'verbose_name': 'Documento Acadêmico',
                'verbose_name_plural': 'Documentos Acadêmicos',
                'ordering': ['-total_downloads', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailyNetworkMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Data da Amostra')),
                ('is_active_day', models.BooleanField(db_index=True, default=True, help_text='Falso caso corresponda a intervalo/pausa acadêmica ou manutenção')),
                ('active_nodes_peak', models.IntegerField(default=0, verbose_name='Pico de Nós Conectados')),
                ('active_nodes_avg', models.FloatField(default=0.0, verbose_name='Média de Nós Ativos')),
                ('active_swarms', models.IntegerField(default=0, verbose_name='Swarms em Atividade')),
                ('total_transfers', models.IntegerField(default=0, verbose_name='Total de Transferências')),
                ('successful_transfers', models.IntegerField(default=0, verbose_name='Transferências Concluídas')),
                ('data_transferred_mb', models.FloatField(default=0.0, verbose_name='Volume Trafegado (MB)')),
                ('avg_download_speed_kbps', models.FloatField(default=0.0, verbose_name='Velocidade Média Download (KB/s)')),
                ('avg_upload_speed_kbps', models.FloatField(default=0.0, verbose_name='Velocidade Média Upload (KB/s)')),
                ('avg_tor_latency_ms', models.FloatField(default=0.0, verbose_name='Latência Média Tor (ms)')),
                ('chunk_integrity_rate', models.FloatField(default=99.6, verbose_name='Taxa de Integridade dos Chunks (%)')),
                ('single_seed_speed_avg_kbps', models.FloatField(default=320.0, verbose_name='Velocidade com 1 Seed (KB/s)')),
                ('multi_seed_speed_avg_kbps', models.FloatField(default=2150.0, verbose_name='Velocidade com Múltiplos Seeds (KB/s)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações do Período de Testes')),
            ],
            options={
                'verbose_name': 'Métrica Diária da Rede',
                'verbose_name_plural': 'Métricas Diárias da Rede',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PeerNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.UUIDField(db_index=True, help_text='Identificador único gerado pelo cliente Desktop', unique=True)),
                ('onion_address', models.CharField(db_index=True, help_text='Endereço Hidden Service v3 (.onion)', max_length=120, unique=True)),
                ('client_version', models.CharField(default='0.0.2', max_length=20)),
                ('country_code', models.CharField(default='BR', help_text='País de origem estimada do relay de saída', max_length=5)),
                ('is_online', models.BooleanField(db_index=True, default=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('total_chunks_served', models.BigIntegerField(default=0, help_text='Chunks servidos como seeder')),
                ('total_bytes_uploaded', models.BigIntegerField(default=0)),
                ('total_bytes_downloaded', models.BigIntegerField(default=0)),
                ('reputation_score', models.FloatField(default=100.0, help_text='Pontuação de confiabilidade e uptime do nó (0 a 100)')),
            ],
            options={
                'verbose_name': 'Nó P2P (Peer)',
                'verbose_name_plural': 'Nós P2P (Peers)',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SwarmSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_seeders', models.IntegerField(verbose_name='Seeders Ativos')),
                ('active_leechers', models.IntegerField(default=0, verbose_name='Leechers Concorrentes')),
                ('swarm_ratio', models.FloatField(default=1.0, verbose_name='Razão S/L')),
                ('health_status', models.CharField(choices=[('EXCELLENT', 'Excelente (>= 5 seeders)'), ('HEALTHY', 'Saudável (2 a 4 seeders)'), ('DEGRADED', 'Degradado (1 seeder solitário)'), ('CRITICAL', 'Crítico (0 seeders online)')], db_index=True, default='HEALTHY', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Instante da Amostra')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swarm_snapshots', to='analytics.academicdocument')),
            ],
            options={
                'verbose_name': 'Snapshot de Swarm',
                'verbose_name_plural': 'Snapshots de Swarm',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransferSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_type', models.CharField(choices=[('DOWNLOAD', 'Download de Documento'), ('UPLOAD', 'Upload / Anúncio Inicial'), ('SWARM_RESEED', 'Replicação Automática Swarm')], db_index=True, default='DOWNLOAD', max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Concluído com Sucesso'), ('FAILED', 'Falha Criptográfica / Hash Incorreto'), ('INTERRUPTED', 'Interrompido pelo Usuário'), ('TIMED_OUT', 'Timeout de Circuito Tor')], db_index=True, default='COMPLETED', max_length=20)),
                ('file_size_bytes', models.BigIntegerField()),
                ('bytes_transferred', models.BigIntegerField()),
                ('chunks_transferred', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('parallel_seeders', models.IntegerField(default=1, help_text='Quantidade de peers que participaram do envio simultâneo de chunks')),
                ('duration_seconds', models.FloatField(verbose_name='Duração (segundos)')),
                ('average_speed_kbps', models.FloatField(db_index=True, verbose_name='Velocidade Média (KB/s)')),
                ('peak_speed_kbps', models.FloatField(verbose_name='Velocidade de Pico (KB/s)')),
                ('tor_circuit_latency_ms', models.FloatField(default=350.0, verbose_name='Latência Tor (ms)')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Início da Transferência')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='analytics.academicdocument')),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_as_source', to='analytics.peernode')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_as_target', to='analytics.peernode')),
            ],
            options={
                'verbose_name': 'Sessão de Transferência',
                'verbose_name_plural': 'Sessões de Transferência',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChunkPerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.IntegerField(verbose_name='Índice do Chunk')),
                ('chunk_size_bytes', models.IntegerField(default=524288)),
                ('latency_ms', models.FloatField(verbose_name='Latência do Chunk (ms)')),
                ('transfer_time_ms', models.FloatField(verbose_name='Tempo de Baixa (ms)')),
                ('verification_passed', models.BooleanField(default=True, verbose_name='Validação Poly1305 Aprovada')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retransmissões')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('seeder_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.peernode')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_logs', to='analytics.transfersession')),
            ],
            options={
                'verbose_name': 'Log de Desempenho de Chunk',
                'verbose_name_plural': 'Logs de Desempenho de Chunks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
