# Generated by Django 5.0.4 on 2026-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peernode',
            name='city',
            field=models.CharField(default='Sorocaba', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='peernode',
            name='node_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Identificação / Local'),
        ),
        migrations.AddField(
            model_name='peernode',
            name='region_state',
            field=models.CharField(default='SP', max_length=10, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='client_version',
            field=models.CharField(default='0.0.2', max_length=20, verbose_name='Versão do Cliente'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='country_code',
            field=models.CharField(default='BR', max_length=5, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='is_online',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Status Online'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='last_seen',
            field=models.DateTimeField(db_index=True, verbose_name='Última Atividade'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='node_id',
            field=models.UUIDField(db_index=True, unique=True, verbose_name='Node ID'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='onion_address',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Endereço Hidden Service (.onion)'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='reputation_score',
            field=models.FloatField(default=100.0, verbose_name='Reputação (%)'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='total_bytes_downloaded',
            field=models.BigIntegerField(default=0, verbose_name='Bytes Baixados'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='total_bytes_uploaded',
            field=models.BigIntegerField(default=0, verbose_name='Bytes Enviados'),
        ),
        migrations.AlterField(
            model_name='peernode',
            name='total_chunks_served',
            field=models.BigIntegerField(default=0, verbose_name='Chunks Servidos (Seed)'),
        ),
    ]
